/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuestionResponses {
    loanAmount: LoanAmount;
    upcomingExpenses: Expenses;
    assetClasses: Array<AssetClass>;
    income: Income;
    familyContribution: FamilyContribution;
}
export interface PersonaScores {
    upcomingExpenseFulfillmentLikelihood: bigint;
    debtProfile: bigint;
    riskAppetite: bigint;
    emergencyBrokeLikelihood: bigint;
    earningPotential: bigint;
}
export enum AssetClass {
    fixed = "fixed",
    stocks = "stocks",
    realEstate = "realEstate",
    other = "other",
    crypto = "crypto"
}
export enum Expenses {
    low = "low",
    high = "high",
    none = "none",
    medium = "medium"
}
export enum FamilyContribution {
    full = "full",
    none = "none",
    partial = "partial"
}
export enum Income {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum LoanAmount {
    none = "none",
    large = "large",
    small = "small",
    medium = "medium"
}
export interface backendInterface {
    calculatePersonaScores(responses: QuestionResponses): Promise<PersonaScores>;
    testCalculateScores(): Promise<void>;
}
import type { AssetClass as _AssetClass, Expenses as _Expenses, FamilyContribution as _FamilyContribution, Income as _Income, LoanAmount as _LoanAmount, QuestionResponses as _QuestionResponses } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async calculatePersonaScores(arg0: QuestionResponses): Promise<PersonaScores> {
        if (this.processError) {
            try {
                const result = await this.actor.calculatePersonaScores(to_candid_QuestionResponses_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculatePersonaScores(to_candid_QuestionResponses_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async testCalculateScores(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.testCalculateScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.testCalculateScores();
            return result;
        }
    }
}
function to_candid_AssetClass_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetClass): _AssetClass {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Expenses_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expenses): _Expenses {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_FamilyContribution_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FamilyContribution): _FamilyContribution {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Income_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Income): _Income {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_LoanAmount_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanAmount): _LoanAmount {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionResponses_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionResponses): _QuestionResponses {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loanAmount: LoanAmount;
    upcomingExpenses: Expenses;
    assetClasses: Array<AssetClass>;
    income: Income;
    familyContribution: FamilyContribution;
}): {
    loanAmount: _LoanAmount;
    upcomingExpenses: _Expenses;
    assetClasses: Array<_AssetClass>;
    income: _Income;
    familyContribution: _FamilyContribution;
} {
    return {
        loanAmount: to_candid_LoanAmount_n3(_uploadFile, _downloadFile, value.loanAmount),
        upcomingExpenses: to_candid_Expenses_n5(_uploadFile, _downloadFile, value.upcomingExpenses),
        assetClasses: to_candid_vec_n7(_uploadFile, _downloadFile, value.assetClasses),
        income: to_candid_Income_n10(_uploadFile, _downloadFile, value.income),
        familyContribution: to_candid_FamilyContribution_n12(_uploadFile, _downloadFile, value.familyContribution)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Income): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Income.low ? {
        low: null
    } : value == Income.high ? {
        high: null
    } : value == Income.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FamilyContribution): {
    full: null;
} | {
    none: null;
} | {
    partial: null;
} {
    return value == FamilyContribution.full ? {
        full: null
    } : value == FamilyContribution.none ? {
        none: null
    } : value == FamilyContribution.partial ? {
        partial: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoanAmount): {
    none: null;
} | {
    large: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == LoanAmount.none ? {
        none: null
    } : value == LoanAmount.large ? {
        large: null
    } : value == LoanAmount.small ? {
        small: null
    } : value == LoanAmount.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expenses): {
    low: null;
} | {
    high: null;
} | {
    none: null;
} | {
    medium: null;
} {
    return value == Expenses.low ? {
        low: null
    } : value == Expenses.high ? {
        high: null
    } : value == Expenses.none ? {
        none: null
    } : value == Expenses.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AssetClass): {
    fixed: null;
} | {
    stocks: null;
} | {
    realEstate: null;
} | {
    other: null;
} | {
    crypto: null;
} {
    return value == AssetClass.fixed ? {
        fixed: null
    } : value == AssetClass.stocks ? {
        stocks: null
    } : value == AssetClass.realEstate ? {
        realEstate: null
    } : value == AssetClass.other ? {
        other: null
    } : value == AssetClass.crypto ? {
        crypto: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AssetClass>): Array<_AssetClass> {
    return value.map((x)=>to_candid_AssetClass_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
