/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LoanAmount = IDL.Variant({
  'none' : IDL.Null,
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const Expenses = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'none' : IDL.Null,
  'medium' : IDL.Null,
});
export const AssetClass = IDL.Variant({
  'fixed' : IDL.Null,
  'stocks' : IDL.Null,
  'realEstate' : IDL.Null,
  'other' : IDL.Null,
  'crypto' : IDL.Null,
});
export const Income = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const FamilyContribution = IDL.Variant({
  'full' : IDL.Null,
  'none' : IDL.Null,
  'partial' : IDL.Null,
});
export const QuestionResponses = IDL.Record({
  'loanAmount' : LoanAmount,
  'upcomingExpenses' : Expenses,
  'assetClasses' : IDL.Vec(AssetClass),
  'income' : Income,
  'familyContribution' : FamilyContribution,
});
export const PersonaScores = IDL.Record({
  'upcomingExpenseFulfillmentLikelihood' : IDL.Nat,
  'debtProfile' : IDL.Nat,
  'riskAppetite' : IDL.Nat,
  'emergencyBrokeLikelihood' : IDL.Nat,
  'earningPotential' : IDL.Nat,
});

export const idlService = IDL.Service({
  'calculatePersonaScores' : IDL.Func([QuestionResponses], [PersonaScores], []),
  'testCalculateScores' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LoanAmount = IDL.Variant({
    'none' : IDL.Null,
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Expenses = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'none' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AssetClass = IDL.Variant({
    'fixed' : IDL.Null,
    'stocks' : IDL.Null,
    'realEstate' : IDL.Null,
    'other' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const Income = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const FamilyContribution = IDL.Variant({
    'full' : IDL.Null,
    'none' : IDL.Null,
    'partial' : IDL.Null,
  });
  const QuestionResponses = IDL.Record({
    'loanAmount' : LoanAmount,
    'upcomingExpenses' : Expenses,
    'assetClasses' : IDL.Vec(AssetClass),
    'income' : Income,
    'familyContribution' : FamilyContribution,
  });
  const PersonaScores = IDL.Record({
    'upcomingExpenseFulfillmentLikelihood' : IDL.Nat,
    'debtProfile' : IDL.Nat,
    'riskAppetite' : IDL.Nat,
    'emergencyBrokeLikelihood' : IDL.Nat,
    'earningPotential' : IDL.Nat,
  });
  
  return IDL.Service({
    'calculatePersonaScores' : IDL.Func(
        [QuestionResponses],
        [PersonaScores],
        [],
      ),
    'testCalculateScores' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };