/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssetClass = { 'fixed' : null } |
  { 'stocks' : null } |
  { 'realEstate' : null } |
  { 'other' : null } |
  { 'crypto' : null };
export type Expenses = { 'low' : null } |
  { 'high' : null } |
  { 'none' : null } |
  { 'medium' : null };
export type FamilyContribution = { 'full' : null } |
  { 'none' : null } |
  { 'partial' : null };
export type Income = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type LoanAmount = { 'none' : null } |
  { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface PersonaScores {
  'upcomingExpenseFulfillmentLikelihood' : bigint,
  'debtProfile' : bigint,
  'riskAppetite' : bigint,
  'emergencyBrokeLikelihood' : bigint,
  'earningPotential' : bigint,
}
export interface QuestionResponses {
  'loanAmount' : LoanAmount,
  'upcomingExpenses' : Expenses,
  'assetClasses' : Array<AssetClass>,
  'income' : Income,
  'familyContribution' : FamilyContribution,
}
export interface _SERVICE {
  'calculatePersonaScores' : ActorMethod<[QuestionResponses], PersonaScores>,
  'testCalculateScores' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];